### ISSUE TITLE
Cloud storage in Jenkins

### ISSUE THREAD

**Issue by martinda** [hynespm/highly-available-jenkins-ecs-efs#1]
Hi @hynespm.

I'm a Jenkins Org Admin in the Google Summer of Code program. Would you be interested in taking this project to Google Summer of Code by adding cloud storage to Jenkins? Let me know. We have a proposal to that effect [here](https://docs.google.com/document/d/12qsvHSJpDaYALQQgzWpWw0-cmu6QOAmhr5THK3T1U0M/edit#heading=h.vhjq4vr0ukxb).

Best,
Martin d'Anjou

**Comment by hynespm** [comment]
This can be closed :)
